import React, { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";

const API = import.meta.env.VITE_API_URL || "/api";
async function api(path, options={}){const token=localStorage.getItem("studytrack_token");const res=await fetch(API+path,{...options,headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{}) ,...(options.headers||{})}});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||"Request failed");return data;}
const fmtHours=m=>`${(Number(m||0)/60).toFixed(1)}h`;
const fmtDate=d=>d?new Date(`${d}T00:00:00`).toLocaleDateString(undefined,{day:"2-digit",month:"short"}):"—";

function App(){const [user,setUser]=useState(null),[role,setRole]=useState("student"),[mode,setMode]=useState("login");useEffect(()=>{const t=localStorage.getItem("studytrack_token");if(t)api("/me").then(x=>setUser(x.user)).catch(()=>localStorage.removeItem("studytrack_token"));},[]);if(!user)return <Auth role={role} setRole={setRole} mode={mode} setMode={setMode} onLogin={setUser}/>;const logout=()=>{localStorage.removeItem("studytrack_token");setUser(null);};return user.role==="teacher"?<TeacherApp user={user} logout={logout}/>:<StudentApp user={user} logout={logout}/>;}

function Auth({role,setRole,mode,setMode,onLogin}){const [form,setForm]=useState({name:"",email:"",password:"",classCode:""}),[error,setError]=useState("");const submit=async e=>{e.preventDefault();setError("");try{const body=mode==="register"?form:{email:form.email,password:form.password,role};const data=await api(mode==="register"?"/auth/register":"/auth/login",{method:"POST",body:JSON.stringify(body)});localStorage.setItem("studytrack_token",data.token);onLogin(data.user);}catch(e){setError(e.message);}};return <main className="auth"><div className="auth-card"><div className="brand">Study<span>Track</span></div><p className="muted">Coaching + self-study progress, finally connected.</p><div className="role-switch"><button className={role==="student"?"active":""} onClick={()=>{setRole("student");setMode("login")}}>Student</button><button className={role==="teacher"?"active":""} onClick={()=>{setRole("teacher");setMode("login")}}>Teacher</button></div><h1>{mode==="login"?`Login as ${role}`:"Create student account"}</h1><form onSubmit={submit}>{mode==="register"&&<input placeholder="Full name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/>}<input type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/><input type="password" placeholder="Password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/>{mode==="register"&&<input placeholder="Class code" value={form.classCode} onChange={e=>setForm({...form,classCode:e.target.value})} required/>}{error&&<div className="error">{error}</div>}<button className="primary" type="submit">{mode==="login"?"Login":"Create account"}</button></form>{role==="student"&&<button className="link" onClick={()=>setMode(mode==="login"?"register":"login")}>{mode==="login"?"New student? Register with class code":"Already registered? Login"}</button>}<div className="demo"><b>Demo accounts</b><br/>Teacher: teacher@coaching.com / teacher123<br/>Student: student@coaching.com / student123</div></div></main>;}

function Layout({user,title,subtitle,children,logout}){return <div className="app"><header><div className="brand small">Study<span>Track</span></div><div className="userbar"><span>{user.name}</span><span className="pill">{user.role}</span><button onClick={logout}>Logout</button></div></header><main className="container"><div className="page-title"><div><h1>{title}</h1><p className="muted">{subtitle||"Track progress. Stay accountable. Improve."}</p></div></div>{children}</main></div>;}
function Stat({label,value,sub,tone=""}){return <div className={`stat ${tone}`}><span>{label}</span><strong>{value}</strong>{sub&&<small>{sub}</small>}</div>}
function Card({title,meta,body,children}){return <div className="card"><div className="card-head"><b>{title}</b>{meta&&<small>{meta}</small>}</div>{body&&<p>{body}</p>}{children}</div>}
function Empty({children="Nothing here yet."}){return <p className="muted empty">{children}</p>}
function BarList({items,labelKey="subject",valueKey="minutes",suffix=" min"}){const max=Math.max(1,...items.map(x=>Number(x[valueKey]||0)));if(!items.length)return <Empty/>;return <div className="bar-list">{items.map((x,i)=><div className="bar-row" key={i}><div><span>{x[labelKey]}</span><b>{x[valueKey]}{suffix}</b></div><div className="bar"><i style={{width:`${Math.max(4,Number(x[valueKey]||0)/max*100)}%`}}/></div></div>)}</div>}
function Activity({items}){if(!items?.length)return <Empty>No recent activity yet.</Empty>;return <div className="activity">{items.map((x,i)=><div className="activity-row" key={i}><span className={`activity-dot ${x.type}`}/><div><b>{x.title}</b><span>{x.student&&`${x.student} • `}{x.detail}{x.value?` • ${x.value}${x.type==="study"?" min":""}`:""}</span></div><small>{fmtDate(x.activity_date)}</small></div>)}</div>}

function TeacherApp({user,logout}){const [data,setData]=useState(null),[tab,setTab]=useState("overview"),[selected,setSelected]=useState(null),[home,setHome]=useState({title:"",description:"",dueDate:""}),[test,setTest]=useState({title:"",subject:"",maxMarks:"",solution:"",testDate:""}),[mark,setMark]=useState({testId:"",studentId:"",marks:"",remark:""}),[loading,setLoading]=useState(false);const load=()=>api("/teacher/overview").then(setData).catch(e=>alert(e.message));useEffect(load,[]);if(!data)return <div className="loading">Loading StudyTrack…</div>;
const addHomework=async e=>{e.preventDefault();setLoading(true);try{await api("/teacher/homework",{method:"POST",body:JSON.stringify(home)});setHome({title:"",description:"",dueDate:""});await load();}catch(e){alert(e.message)}finally{setLoading(false)}};
const addTest=async e=>{e.preventDefault();setLoading(true);try{await api("/teacher/tests",{method:"POST",body:JSON.stringify(test)});setTest({title:"",subject:"",maxMarks:"",solution:"",testDate:""});await load();}catch(e){alert(e.message)}finally{setLoading(false)}};
const addMark=async e=>{e.preventDefault();try{await api("/teacher/marks",{method:"POST",body:JSON.stringify(mark)});setMark({testId:"",studentId:"",marks:"",remark:""});await load();alert("Marks saved and synced to the student dashboard.");}catch(e){alert(e.message)}};
return <Layout user={user} logout={logout} title="Teacher dashboard" subtitle="See study activity, performance and homework completion in one place."><nav className="tabs">{["overview","activity","homework","tests","students"].map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x}</button>)}</nav>
{tab==="overview"&&<><div className="grid four"><Stat label="Students" value={data.stats.students}/><Stat label="Class average" value={`${data.stats.classAverage}%`}/><Stat label="Study time" value={fmtHours(data.stats.totalStudyMinutes)}/><Stat label="Tests" value={data.stats.tests}/></div><div className="dashboard-grid"><section className="panel"><div className="section-head"><h2>Student snapshot</h2><span className="muted">Live from study logs + marks</span></div>{data.students.length?<div className="table-wrap"><table><thead><tr><th>Student</th><th>Study</th><th>Avg score</th><th>Homework</th><th>Tests</th></tr></thead><tbody>{data.students.map(s=><tr key={s.id}><td><b>{s.name}</b><small>{s.email}</small></td><td>{fmtHours(s.study_minutes)}</td><td>{Number(s.average_percentage).toFixed(1)}%</td><td>{s.homework_completed}/{s.homework_total}</td><td>{s.tests_taken}</td></tr>)}</tbody></table></div>:<Empty/>}</section><section className="panel"><div className="section-head"><h2>Recent activity</h2><button className="link" onClick={()=>setTab("activity")}>View all</button></div><Activity items={data.recentActivity.slice(0,8)}/></section></div></>}
{tab==="activity"&&<section className="panel"><div className="section-head"><h2>Class recent activity</h2><span className="muted">Study logs, submissions and test marks</span></div><Activity items={data.recentActivity}/></section>}
{tab==="homework"&&<section className="panel"><h2>Create homework</h2><form className="form-grid" onSubmit={addHomework}><input placeholder="Title" value={home.title} onChange={e=>setHome({...home,title:e.target.value})} required/><input type="date" value={home.dueDate} onChange={e=>setHome({...home,dueDate:e.target.value})}/><textarea placeholder="Description / instructions" value={home.description} onChange={e=>setHome({...home,description:e.target.value})}/><button className="primary" disabled={loading}>{loading?"Publishing…":"Publish homework"}</button></form><h2>Published homework</h2><div className="list">{data.homework.map(h=><Card key={h.id} title={h.title} meta={`Due ${fmtDate(h.due_date)}`} body={h.description}><div className="progress-line"><span>{h.submitted_count}/{h.student_count} submitted</span><div><i style={{width:`${h.student_count?Math.round(h.submitted_count*100/h.student_count):0}%`}}/></div></div></Card>)}</div></section>}
{tab==="tests"&&<section className="panel"><h2>Create test</h2><form className="form-grid" onSubmit={addTest}><input placeholder="Test title" value={test.title} onChange={e=>setTest({...test,title:e.target.value})} required/><input placeholder="Subject" value={test.subject} onChange={e=>setTest({...test,subject:e.target.value})} required/><input type="number" min="1" placeholder="Max marks" value={test.maxMarks} onChange={e=>setTest({...test,maxMarks:e.target.value})} required/><input type="date" value={test.testDate} onChange={e=>setTest({...test,testDate:e.target.value})}/><textarea placeholder="Solution / analysis" value={test.solution} onChange={e=>setTest({...test,solution:e.target.value})}/><button className="primary">Publish test</button></form><h2>Enter / update marks</h2><form className="form-grid" onSubmit={addMark}><select value={mark.testId} onChange={e=>setMark({...mark,testId:e.target.value})} required><option value="">Select test</option>{data.tests.map(t=><option value={t.id} key={t.id}>{t.title}</option>)}</select><select value={mark.studentId} onChange={e=>setMark({...mark,studentId:e.target.value})} required><option value="">Select student</option>{data.students.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select><input type="number" step="0.1" min="0" placeholder="Marks" value={mark.marks} onChange={e=>setMark({...mark,marks:e.target.value})} required/><input placeholder="Remark" value={mark.remark} onChange={e=>setMark({...mark,remark:e.target.value})}/><button className="primary">Save marks</button></form><div className="list">{data.tests.map(t=><Card key={t.id} title={t.title} meta={`${t.subject} • ${t.max_marks} marks • ${fmtDate(t.test_date)}`} body={t.solution||"No solution published yet."}><span className="badge">{t.marked_count}/{data.students.length} marked</span></Card>)}</div></section>}
{tab==="students"&&<section className="panel"><div className="student-grid">{data.students.map(s=><button className={`student-card ${selected===s.id?"selected":""}`} key={s.id} onClick={()=>setSelected(s.id)}><b>{s.name}</b><small>{fmtHours(s.study_minutes)} study • {Number(s.average_percentage).toFixed(1)}% avg</small></button>)}</div>{selected?<StudentAnalytics id={selected}/>:<Empty>Select a student to open detailed analytics.</Empty>}</section>}</Layout>;}

function StudentAnalytics({id}){const [a,setA]=useState(null);useEffect(()=>{setA(null);api(`/teacher/student/${id}/analytics`).then(setA).catch(e=>alert(e.message));},[id]);if(!a)return <p className="loading-inline">Loading analytics…</p>;return <div className="analytics"><div className="section-head"><div><h2>{a.student.name}</h2><span className="muted">Study activity vs test performance</span></div><span className="pill">{a.student.email}</span></div><div className="grid four"><Stat label="Average" value={`${a.averagePercentage}%`}/><Stat label="Improvement" value={`${a.improvementPercentage>=0?"+":""}${a.improvementPercentage}%`}/><Stat label="Study time" value={fmtHours(a.totalStudyMinutes)}/><Stat label="Tests" value={a.scores.length}/></div><div className="dashboard-grid"><section className="panel nested"><h3>Study by subject</h3><BarList items={a.studyBySubject}/></section><section className="panel nested"><h3>Score trend</h3>{a.scores.length?<div className="score-list">{a.scores.map(s=><div className="score-row" key={s.id}><span>{fmtDate(s.test_date)} · {s.title}</span><b>{s.marks}/{s.max_marks}</b><em>{s.percentage}%</em></div>)}</div>:<Empty/>}</section></div><section className="panel nested"><h3>Study-hours → test-performance comparison</h3>{a.paired.length?<div className="table-wrap"><table><thead><tr><th>Test</th><th>Score</th><th>Study minutes accumulated before test</th></tr></thead><tbody>{a.paired.map((x,i)=><tr key={i}><td>{x.test}</td><td>{x.percentage}%</td><td>{x.studyMinutesBeforeTest} min</td></tr>)}</tbody></table></div>:<Empty>No test records yet.</Empty>}</section><section className="panel nested"><h3>Homework status</h3><div className="status-grid">{a.homework.map(h=><div className="status-card" key={h.id}><b>{h.title}</b><span className={`status ${h.status}`}>{h.status}</span><small>Due {fmtDate(h.due_date)}</small></div>)}</div></section></div>}

function StudentApp({user,logout}){const [data,setData]=useState(null),[tab,setTab]=useState("home"),[log,setLog]=useState({category:"self-study",subject:"",minutes:"",studyDate:new Date().toISOString().slice(0,10),note:""}),[note,setNote]=useState({}),[saving,setSaving]=useState(false);const load=()=>api("/student/dashboard").then(setData).catch(e=>alert(e.message));useEffect(load,[]);if(!data)return <div className="loading">Loading StudyTrack…</div>;const submit=async id=>{try{await api(`/student/homework/${id}/submit`,{method:"POST",body:JSON.stringify({note:note[id]||""})});await load();}catch(e){alert(e.message)}};const addLog=async e=>{e.preventDefault();setSaving(true);try{await api("/student/study-log",{method:"POST",body:JSON.stringify(log)});setLog({...log,subject:"",minutes:"",note:""});await load();}catch(e){alert(e.message)}finally{setSaving(false)}};const total=data.stats.total_study_minutes||0;return <Layout user={user} logout={logout} title={`Welcome back, ${user.name.split(" ")[0]}`} subtitle="Your study time, tests and homework are now synced automatically."><nav className="tabs">{["home","study","tests","homework"].map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x}</button>)}</nav>
{tab==="home"&&<><div className="grid four"><Stat label="Average score" value={`${Number(data.stats.average_percentage).toFixed(1)}%`}/><Stat label="Study hours" value={fmtHours(total)}/><Stat label="Homework done" value={`${data.stats.homework_completed}/${data.stats.homework_total}`}/><Stat label="Tests taken" value={data.stats.tests_taken}/></div><div className="dashboard-grid"><section className="panel"><div className="section-head"><h2>Homework status</h2><button className="link" onClick={()=>setTab("homework")}>Open homework</button></div><div className="status-grid">{data.homework.slice(0,6).map(h=><div className="status-card" key={h.id}><b>{h.title}</b><span className={`status ${h.status}`}>{h.status}</span><small>Due {fmtDate(h.due_date)}</small></div>)}</div></section><section className="panel"><div className="section-head"><h2>Recent activity</h2></div><Activity items={data.recentActivity}/></section></div></>}
{tab==="study"&&<><section className="panel"><div className="section-head"><div><h2>Log study time</h2><span className="muted">Every saved session immediately updates teacher analytics.</span></div></div><form className="form-grid four-cols" onSubmit={addLog}><select value={log.category} onChange={e=>setLog({...log,category:e.target.value})}><option value="self-study">Self-study</option><option value="tuition">Tuition</option><option value="outside">Outside</option></select><input placeholder="Subject" value={log.subject} onChange={e=>setLog({...log,subject:e.target.value})} required/><input type="number" min="1" placeholder="Minutes" value={log.minutes} onChange={e=>setLog({...log,minutes:e.target.value})} required/><input type="date" value={log.studyDate} onChange={e=>setLog({...log,studyDate:e.target.value})}/><input placeholder="Note (optional)" value={log.note} onChange={e=>setLog({...log,note:e.target.value})}/><button className="primary" disabled={saving}>{saving?"Saving…":"Add session"}</button></form></section><div className="dashboard-grid"><section className="panel"><h2>Study by subject</h2><BarList items={data.studyBySubject}/></section><section className="panel"><h2>Recent study sessions</h2>{data.logs.length?<div className="score-list">{data.logs.slice(0,15).map(x=><div className="score-row" key={x.id}><span>{fmtDate(x.study_date)} · {x.subject}</span><b>{x.minutes} min</b><em>{x.category}</em></div>)}</div>:<Empty/>}</section></div></>}
{tab==="tests"&&<section className="panel"><h2>Tests & solutions</h2>{data.tests.length?<div className="list">{data.tests.map(t=><Card key={t.id} title={t.title} meta={`${t.subject} • ${fmtDate(t.test_date)}`} body={t.marks==null?`Not marked yet. Solution: ${t.solution||"Not published"}`:`${t.marks}/${t.max_marks} (${t.percentage}%) • ${t.remark||"No remark"}. Solution: ${t.solution||"Not published"}`}/>)}</div>:<Empty/>}</section>}
{tab==="homework"&&<section className="panel"><h2>Homework</h2>{data.homework.length?<div className="list">{data.homework.map(h=><Card key={h.id} title={h.title} meta={`Due ${fmtDate(h.due_date)}`} body={h.description}><div className="submission"><span className={`status ${h.status}`}>{h.status}</span><input placeholder="Submission note" value={note[h.id]??h.submission_note??""} onChange={e=>setNote({...note,[h.id]:e.target.value})}/><button className="primary small-btn" onClick={()=>submit(h.id)}>{h.status==="completed"?"Update submission":"Submit homework"}</button></div></Card>)}</div>:<Empty/>}</section>}
</Layout>;}

createRoot(document.getElementById("root")).render(<App/>);
